# Generated by Django 4.2.6 on 2023-10-25 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.datetime.now)),
                ('end', models.DateField()),
                ('description', models.CharField(default='', max_length=256)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
